[package]
name = "api-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
core-backend = { version = "0.1.0", path = "../core-backend" }

axum = "0.8.1"
axum-test = "17.1.0"
chrono = "0.4.39"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio", "chrono"] }
